### PR TITLE
Fix escaping in command string.

### LINKED ISSUE #10: Ensure that quotes are properly escaped in the command output.
I thought this was working. Needs investigation and a test if there isn't one already.
https://www.youtube.com/watch?v=yOT-ZSNCexg&lc=UgyKMclOo5qwxClBovR4AaABAg.9n8mFJMvw4A9nKKVgm9rgq

### PR DESCRIPTION
**Pull request by NightlyNexus**
The JSON string is not supposed to be double-escaped. Only the escape characters are supposed to be double-escaped.

Closes #10

### CODE REVIEW

File: gutencraft/src/commonTest/kotlin/CommandTest.kt [hunk 1]
```diff
@@ -14,9 +14,9 @@ class CommandTest {
   }
 
   @Test fun escapes() {
-    val pages = pages("\\\nf")
+    val pages = pages("begin... \\\nf\" ' ...end")
     assertEquals(
-      """/give @p written_book{pages:['{"text":"\\\\\\nf"}'],title:"<Insert book name>",author:"<Insert author>"}""".trimMargin(),
+      """/give @p written_book{pages:['{"text":"begin... \\\\\\nf\\" ' ...end"}'],title:"<Insert book name>",author:"<Insert author>"}""".trimMargin(),
```
Comment (NightlyNexus) [inline gutencraft/src/commonTest/kotlin/CommandTest.kt:19]: This previously generated `\\\"` to escape `"`" but now correctly generates `\\"`.
